[project]
name = "web"
version = "0.1.0"
description = ""
authors = [
    {name = "Joe Gasewicz",email = "joegasewicz@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "acornio (>=0.0.2,<0.0.3)",
    "bobtail (>=0.3.0,<0.4.0)",
    "bobtail-cors (>=0.0.1,<0.0.2)",
    "bobtail-logger (>=0.0.1,<0.0.2)",
    "bobtail-upload (>=0.0.1,<0.0.2)",
    "bobtail-jinja2 (>=0.0.2,<0.0.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
